# Vorlage:
# https://medium.com/towards-data-engineering/running-a-postgresql-and-pgadmin4-instance-using-docker-compose-c6dd6e6e03bb
#
# Verbindung von pgadmin zu postgres muss manuell eingerichtet werden, siehe
# "5. Connecting to the Database server" auf der oben verlinkten Seite.

services:
  postgres:
    image: postgres:18.3 # für neue Version siehe https://hub.docker.com/_/postgres
    restart: "no"
    environment:
      POSTGRES_USER: datenbank-nutzer
      POSTGRES_PASSWORD: g3h3im
      POSTGRES_DB: meine_postgres_db

    # ACHTUNG: ohne Definition eines Volumes gehen die Daten verloren
    #          wenn der Container gelöscht wird
    # volumes:
    #   - "postgres-data:/var/lib/postgresql/data"

    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.14.0 # Für neue Version siehe: https://hub.docker.com/r/dpage/pgadmin4
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: pg-admin-nutzer@test.de
      PGADMIN_DEFAULT_PASSWORD: pg-admin-geheim
    ports:
      - "5050:80"