image:
    file: .gitpod.Dockerfile

tasks:
  - name: Verwendungszähler
    command: echo -n $(date '+%d.%m.%Y') >> GitPodVerwendungsZaehler.log

# Damit die beiden HTTP-Ports nicht nach jedem Neustart des Workspaces neu
# freigegeben werden müssen.
ports:
  - name: Bildergallerie
    port: 8080
    onOpen: open-browser 
    visibility: public
  - name: pgAdmin
    port: 5050
    onOpen: open-browser 
    visibility: public
    