
spring.datasource.url=jdbc:mariadb://localhost:3306/bildergallerie
spring.datasource.username=mein_mariadb_nutzer
spring.datasource.password=g3h3im
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Auto-Commit deaktivieren
spring.datasource.hikari.auto-commit=false

spring.h2.console.enabled=false

# Information für http://localhost:8080/actuator/info
info.app.name=Bildergallerie (MariaDB)
